pipeline {
    agent any
    environment { 
        CI = 'false'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Deploy') {
            steps {
                sh "chmod +x -R ./scripts"
                sh './scripts/deploy.sh'
            }
        }
    }
}