# Generated by Django 3.1.7 on 2021-06-20 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import insta_backend.file_utils
import insta_backend.models
import insta_backend.storage


class Migration(migrations.Migration):

    dependencies = [
        ('insta_backend', '0005_auto_20210613_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile_photo',
            field=models.ImageField(storage=insta_backend.storage.OverwriteStorage(), upload_to=insta_backend.models.get_profile_picture_path),
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=insta_backend.file_utils.get_user_images_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
