# Generated by Django 3.1.7 on 2021-06-26 14:24

from django.db import migrations, models
import insta_backend.storage


class Migration(migrations.Migration):

    dependencies = [
        ('insta_backend', '0006_auto_20210620_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(storage=insta_backend.storage.MediaStorage(), upload_to=''),
        ),
    ]
