# Generated by Django 3.1.7 on 2021-06-26 15:17

from django.db import migrations, models
import insta_backend.file_utils
import insta_backend.storage


class Migration(migrations.Migration):

    dependencies = [
        ('insta_backend', '0007_auto_20210626_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='image',
            field=models.ImageField(storage=insta_backend.storage.MediaStorage(), upload_to=insta_backend.file_utils.get_user_images_path),
        ),
    ]
