# Generated by Django 3.1.7 on 2021-07-04 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_backend', '0008_auto_20210626_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_customuser_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='_customuser_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
