# Generated by Django 3.1.7 on 2021-10-15 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta_backend', '0009_auto_20210704_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searched_user', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searching_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
