branch-defaults:
  default:
    environment: Photosharebackend-env
    group_suffix: null
global:
  application_name: photoshare_backend
  branch: null
  default_ec2_keyname: aws-eb-photoshare
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
